Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

-- Deliveries
Config.ShopsInvJsonFile = './json/shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 500
Config.RewardItem = 'water_bottle'
Config.Fuel = 'cdn-fuel'

Config.DeliveryLocations = {
    ['main'] = { label = 'GO Postal', coords = vector4(69.0862, 127.6753, 79.2123, 156.7736) },
    ['vehicleWithdraw'] = vector4(71.9318, 120.8389, 79.0823, 160.5110),
    ['vehicleDeposit'] = vector3(62.7282, 124.9846, 79.0926),
    ['stores'] = {} -- auto generated
}

Config.Vehicles = {
    ['boxville2'] = { ['label'] = 'Boxville StepVan', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
    ['normal'] = {
        { name = "tosti", price = 2, amount = 50, },
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "kurkakola", price = 2, amount = 50, },
        { name = "twerks_candy", price = 2, amount = 50, },
        { name = "snikkel_candy", price = 2, amount = 50, },
        { name = "sandwich", price = 2, amount = 50, },
        { name = "bandage", price = 100, amount = 50, },
        { name = "lighter", price = 2, amount = 50, },
        { name = "rolling_paper", price = 2, amount = 5000,  },
        { name = "clothing_bag", price = 2, amount = 5000,  },
        { name = "blueberry_elfbar", price = 22, amount = 50,  },
        { name = "bubblegum_elfbar", price = 22, amount = 50,  },
        { name = "cheesecake_elfbar", price = 22, amount = 50,  },
        { name = "cherry_elfbar", price = 22, amount = 50,  },
        { name = "cola_elfbar", price = 22, amount = 50,  },
        { name = "doubleapple_elfbar", price = 22, amount = 50,  },
        { name = "elfbull_elfbar", price = 22, amount = 50,  },
        { name = "grape_elfbar", price = 22, amount = 50,  },
        { name = "greenapple_elfbar", price = 22, amount = 50,  },
        { name = "mango_elfbar", price = 22, amount = 50,  },
        { name = "strawberryice_elfbar", price = 22, amount = 50,  },
        { name = "watermelon_elfbar", price = 22, amount = 50,  },
    },
    ['liquor'] = {
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 70000, amount = 50, },
    },
    ['hardware'] = {
        { name = "lockpick", price = 200, amount = 50, },
        { name = "weapon_wrench", price = 250, amount = 250, },
        { name = "weapon_hammer", price = 250, amount = 250, },
        { name = "weapon_bat", price = 500, amount = 50,  requiredGang = { "lostmc" } },  -- Gang only options in stores
        { name = "repairkit", price = 250, amount = 50,  requiredJob = { ["mechanic"] = 0, ["police"] = 0 } },
        { name = "screwdriverset", price = 350, amount = 50, },
        -- { name = "trowel", price = 50, amount = 50, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "firework1", price = 50, amount = 50, },
        { name = "firework2", price = 50, amount = 50, },
        { name = "firework3", price = 50, amount = 50, },
        { name = "firework4", price = 50, amount = 50, },
        { name = "fitbit", price = 400, amount = 150, },
        { name = "cleaningkit", price = 150, amount = 150, },
        { name = "microfibercloth", price = 25, amount = 10, info = {} },
        { name = "blox", price = 50, amount = 10, info = {} },
        { name = "nylonrope", price = 50, amount = 10, info = {} },
        { name = "blowtorch", price = 50, amount = 10, info = {} },
        { name = "laserdrill", price = 50, amount = 10, info = {} },
        { name = "advancedrepairkit", price = 500, amount = 50,  requiredJob = { ["mechanic"] = 0 } },
    },
    ['weedshop'] = {
        { name = "joint", price = 10, amount = 1000, },
        { name = "weapon_poolcue", price = 100, amount = 1000, },
        { name = "weed_nutrition", price = 20, amount = 1000, },
        { name = "empty_weed_bag", price = 2, amount = 1000, },
        { name = "rolling_paper", price = 2, amount = 1000, },
        { name = 'bakingsoda',   price = 50,   amount = 1000, },
        { name = 'emptyvial',    price = 40,   amount = 1000, },
        { name = 'needle',    	price = 60,   amount = 1000, },
    },
    ['gearshop'] = {
        { name = 'diving_gear', price = 2500, amount = 10 },
        { name = 'jerry_can',   price = 200,  amount = 50 },
    },
    ['leisureshop'] = {
        { name = 'parachute',   price = 2500, amount = 10 },
        { name = 'binoculars',  price = 50,   amount = 50 },
        { name = 'diving_gear', price = 2500, amount = 10 },
        { name = 'diving_fill', price = 500,  amount = 10 },
    },
    ['weapons'] = {
        { name = "weapon_knife", price = 250, amount = 250, },
        { name = "weapon_bat", price = 250, amount = 250, },
        { name = "weapon_hatchet",price = 250, amount = 250, },
        { name = "weapon_pistol", price = 2500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_snspistol", price = 1500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_vintagepistol", price = 4000, amount = 5, requiresLicense = {"weapon", "hunting"}, requiresItem = {"weaponlicense", "huntinglicense"} },
        { name = "pistol_ammo", price = 250, amount = 250, },
    },
    ["blackmarket"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_shiv", price = 1000, amount = 20 },
        { name = "weapon_navyrevolver", price = 3000, amount = 5 },
        { name = "weapon_gadgetpistol", price = 4000, amount = 5 },
        { name = "weapon_katana", price = 4000, amount = 20 },
        { name = "weapon_m1911", price = 10000, amount = 5 },
        { name = "weapon_mossberg", price = 18000, amount = 5 },
        { name = "weapon_m110", price = 22000, amount = 5 },
        { name = "weapon_m70", price = 25000, amount = 5 },
        { name = "weapon_carbinerifle_mk2", price = 28000, amount = 5 },
    },
    ["blackmarket2"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_karambit", price = 1000, amount = 20 },
        { name = "weapon_revolver_mk2", price = 5000, amount = 5 },
        { name = "weapon_doubleaction", price = 6000, amount = 5 },
        { name = "weapon_de", price = 10000, amount = 5 },
        { name = "weapon_smg_mk2", price = 25000, amount = 5 },
        { name = "weapon_hk416", price = 25000, amount = 5 },
        { name = "weapon_ak47", price = 28000, amount = 5 },
        { name = "weapon_gusenberg", price = 48000, amount = 5 },
    },
    ["blackmarket3"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_sledgehammer", price = 1500, amount = 20 },
        { name = "weapon_ceramicpistol", price = 10000, amount = 5 },
        { name = "weapon_glock18c", price = 12000, amount = 5 },
        { name = "weapon_mp9", price = 28000, amount = 5 },
        { name = "weapon_mp5", price = 28000, amount = 5 },
        { name = "weapon_aks74", price = 28000, amount = 5 },
        { name = "weapon_heavysniper_mk2", price = 40000, amount = 5 },
    },
    ["blackmarket4"] = {
        { name = "shotgun_ammo", price = 250, amount = 25 },
        { name = "rifle_ammo", price = 250, amount = 25 },
        { name = "snp_ammo", price = 250, amount = 25 },
        { name = "mg_ammo", price = 250, amount = 25 },
        { name = "smg_ammo", price = 250, amount = 25 },
        { name = "weapon_dagger", price = 2000, amount = 20 },
        { name = "weapon_fnx45", price = 10000, amount = 5 },
        { name = "weapon_m9", price = 10000, amount = 5 },
        { name = "weapon_pumpshotgun_mk2", price = 18000, amount = 5 },
        { name = "weapon_uzi", price = 25000, amount = 5 },
        { name = "weapon_mac10", price = 25000, amount = 5 },
        { name = "weapon_ak74", price = 28000, amount = 5 },
        { name = "weapon_combatmg_mk2", price = 56000, amount = 5 },
    },
    ["blackmarket5"] = {
        { name = "gruppesechstablet", price = 1200, amount = 25 },
        { name = "remote_bomb", price = 1200, amount = 25 },
        { name = "ignition_bomb", price = 1200, amount = 25 },
        { name = "impact_bomb", price = 1200, amount = 25 },
        { name = "firelighter", price = 1200, amount = 25 },
        { name = 'ifishingrod', price = 1000, amount = 100 }, -- mz-fishing
        { name = 'ifishingbait', price = 10, amount = 5000 }, -- mz-fishing
        -- { name = "sodiumbicarbonate", price = 8, amount = 25 },
        -- { name = "plasticjerrycan", price = 20, amount = 25 },
    },
    ['prison'] = {
        { name = 'sandwich',     price = 4, amount = 50 },
        { name = 'water_bottle', price = 4, amount = 50 },
    },
    ['police'] = {
        -- weapons
        { name = 'weapon_nightstick',   price = 75,  amount = 5 },
        { name = 'weapon_flashlight',   price = 75,  amount = 5 },
        { name = 'weapon_colbaton',     price = 75,  amount = 5 },
        { name = 'weapon_bzgas',        price = 100, amount = 20 },
        { name = 'weapon_prolaser4',    price = 100, amount = 5 },
        { name = 'weapon_taser',        price = 125, amount = 5 },
        { name = 'weapon_stungun',      price = 125, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_beanbagshotgun', price = 100, amount = 5 },
        { name = 'weapon_pistol',       price = 125, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_glock22',      price = 150, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_remington',    price = 225, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_pumpshotgun',  price = 225, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_smg',          price = 225, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', label = '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_m4',           price = 225, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_carbinerifle', price = 250, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = '3x Scope' } } } },
        { name = 'weapon_ar15',         price = 225, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = 'Scope' }, {component = "COMPONENT_AT_AR_AFGRIP", label = "AF-Grip"} } } },
        { name = 'weapon_scarh',        price = 250, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_heavysniper',  price = 250, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_mk14',         price = 125, amount = 5, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_LARGE', label = 'Scope' } } } },
        -- ammo
        { name = 'stungun_ammo',        price = 10,  amount = 50 },
        { name = 'pistol_ammo',         price = 10,  amount = 50 },
        { name = 'smg_ammo',            price = 10,  amount = 50 },
        { name = 'shotgun_ammo',        price = 10,  amount = 50 },
        { name = 'rifle_ammo',          price = 10,  amount = 50 },
        { name = 'snp_ammo',            price = 10,  amount = 50 },
        -- meds
        { name = 'ifaks',               price = 100, amount = 10 },
        -- misc
        { name = 'handcuffs',           price = 75,  amount = 5 },
        { name = 'cuffkeys',            price = 25,  amount = 20 },
        { name = 'ziptie',              price = 25,  amount = 20 },
        { name = 'flush_cutter',        price = 25,  amount = 5 },
        { name = 'armor',               price = 100, amount = 20 },
        { name = 'heavyarmor',          price = 125, amount = 20 },
        { name = 'radio',               price = 150, amount = 50 },
        { name = 'spikestrip',          price = 75,  amount = 20 },
        { name = 'police_stormram',     price = 50,  amount = 50 },
        { name = 'policetablet',        price = 75,  amount = 5 },
        { name = 'tunerlaptop',         price = 100, amount = 10 },
        -- evidence
        { name = 'nikon',               price = 25,  amount = 5 },
        { name = 'empty_evidence_bag',  price = 20,  amount = 50 },
        { name = 'uvlight',             price = 75,  amount = 5 },
        { name = 'gsrtestkit',          price = 50,  amount = 15 },
        { name = 'dnatestkit',          price = 50,  amount = 15 },
        { name = 'drugtestkit',         price = 50,  amount = 15 },
        { name = 'breathalyzer',        price = 50,  amount = 15 },
        { name = 'accesstool',          price = 50,  amount = 15 },
        { name = 'fingerprintreader',   price = 50,  amount = 15 },
        { name = 'sdcard',              price = 10,  amount = 5 },
        { name = 'fingerprintkit',      price = 50,  amount = 15 },
        { name = 'mikrosil',            price = 50,  amount = 15 },
        { name = 'fingerprinttape',     price = 50,  amount = 15 },
    },
    ['ambulance'] = {
        { name = 'radio',                   price = 150, amount = 5 },
        { name = 'bandage',                 price = 25,  amount = 50 },
        { name = 'painkillers',             price = 25,  amount = 50 },
        { name = 'firstaid',                price = 25,  amount = 50 },
        { name = 'weapon_flashlight',       price = 75,  amount = 5 },
        { name = 'weapon_fireextinguisher', price = 50,  amount = 15 },
    },
    ['mechanic'] = {
        { name = "spanner", price = 75, amount = 50 },
        { name = "adjustable_spanner", price = 95, amount = 50, },
        { name = "pliers", price = 50, amount = 50, },
        { name = "buzz_saw", price = 180, amount = 50, },
        { name = "impact_driver", price = 150, amount = 50, },
        { name = "towremote", price = 50, amount = 50, requiredJob = { ["sadot"] = 0 } },
    },
    ["electronics"] = {
        { name = "phone", price = 850, amount = 50 },
        { name = "radio", price = 250, amount = 50, },
        { name = "screwdriverset", price = 350, amount = 50, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "fitbit", price = 400, amount = 150, },
        { name = "powerbank", price = 30, amount = 50, },
        { name = "tablet", price = 200, amount = 50, },
    },
    ["fishing"] = { -- mz-fishing
        { name = 'fishingrod', price = 100, amount = 100 },
        { name = 'fishingbait', price = 1, amount = 5000 },
    },
}

Config.Locations = {
    -- 24/7 Locations
    ['247supermarket'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(24.47, -1346.62, 29.5, 271.66),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07),
        ['useStock'] = true
    },

    ['247supermarket2'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ['247supermarket3'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ['247supermarket4'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ['247supermarket5'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ['247supermarket6'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(549.13, 2670.85, 42.16, 99.39),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ['247supermarket7'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ['247supermarket8'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2556.66, 380.84, 108.62, 356.67),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ['247supermarket9'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(372.66, 326.98, 103.57, 253.73),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    -- LTD Gasoline Locations
    ['ltdgasoline'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },

    ['ltdgasoline2'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-706.06, -913.97, 19.22, 88.04),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ['ltdgasoline3'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ['ltdgasoline4'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1164.71, -322.94, 69.21, 101.72),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ['ltdgasoline5'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    -- Rob's Liquor Locations
    ['robsliquor'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ['robsliquor2'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ['robsliquor3'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ['robsliquor4'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ['robsliquor5'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1134.2, -982.91, 46.42, 277.24),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    -- Hardware Store Locations
    ['hardware'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(45.68, -1749.04, 29.61, 53.13),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(89.15, -1745.29, 30.09, 315.25)
    },

    ['hardware2'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['hardware3'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },

    -- Digital Den
    ['digitalden1'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(391.76, -832.79, 29.29, 223.77),
        ['ped'] = 's_m_y_strvend_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-calculator',
        ['targetLabel'] = 'Digital Den',
        ['products'] = Config.Products['electronics'],
        ['showblip'] = true,
        ['blipsprite'] = 619,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 7,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },
    ['digitalden2'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(1136.99, -473.13, 66.53, 254.85),
        ['ped'] = 's_m_y_strvend_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-calculator',
        ['targetLabel'] = 'Digital Den',
        ['products'] = Config.Products['electronics'],
        ['showblip'] = true,
        ['blipsprite'] = 619,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 7,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },
    ['digitalden3'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(-509.55, 278.63, 83.31, 176.65),
        ['ped'] = 's_m_y_strvend_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-calculator',
        ['targetLabel'] = 'Digital Den',
        ['products'] = Config.Products['electronics'],
        ['showblip'] = true,
        ['blipsprite'] = 619,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 7,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },
    ['digitalden4'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(-656.27, -854.73, 24.5, 359.39),
        ['ped'] = 's_m_y_strvend_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-calculator',
        ['targetLabel'] = 'Digital Den',
        ['products'] = Config.Products['electronics'],
        ['showblip'] = true,
        ['blipsprite'] = 619,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 7,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },
    ['digitalden5'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(-1088.29, -254.3, 37.76, 252.7),
        ['ped'] = 's_m_y_strvend_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-calculator',
        ['targetLabel'] = 'Digital Den',
        ['products'] = Config.Products['electronics'],
        ['showblip'] = true,
        ['blipsprite'] = 619,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 7,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },

    -- Ammunation Locations
    ['ammunation'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-661.96, -933.53, 21.83, 177.05),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-660.61, -938.14, 21.83, 167.22)
    },
    ['ammunation2'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(809.68, -2159.13, 29.62, 1.43),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(820.97, -2146.7, 28.71, 359.98)
    },
    ['ammunation3'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1687.17, 3755.47, 34.34, 163.69)
    },
    ['ammunation4'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-341.72, 6098.49, 31.32, 11.05)
    },
    ['ammunation5'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(253.63, -51.02, 69.94, 72.91),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(249.0, -50.64, 69.94, 60.71)
    },
    ['ammunation6'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(23.0, -1105.67, 29.8, 162.91),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-5.82, -1107.48, 29.0, 164.32)
    },
    ['ammunation7'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(2567.48, 292.59, 108.73, 349.68),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2578.77, 285.53, 108.61, 277.2)
    },
    ['ammunation8'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1127.67, 2708.18, 18.8, 41.76)
    },
    ['ammunation9'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(841.92, -1035.32, 28.19, 1.56),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(847.83, -1020.36, 27.88, 88.29)
    },
    ['ammunation10'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1302.44, -385.23, 36.62, 303.79)
    },
    ['ammunation11'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3183.6, 1084.35, 20.84, 68.13)
    },

    -- Weedshop Locations
    ['weedshop'] = {
        ['label'] = 'Smoke On The Water',
        ['coords'] = vector4(-1168.26, -1573.2, 4.66, 105.24),
        ['ped'] = 'a_m_y_hippy_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Weed Shop',
        ['products'] = Config.Products['weedshop'],
        ['showblip'] = true,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1162.13, -1568.57, 4.39, 328.52)
    },

    -- Sea Word Locations
    ['seaword'] = {
        ['label'] = 'Sea Word',
        ['coords'] = vector4(-1687.03, -1072.18, 13.15, 52.93),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Sea Word',
        ['products'] = Config.Products['gearshop'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1674.18, -1073.7, 13.15, 333.56)
    },

    -- Leisure Shop Locations
    ['leisureshop'] = {
        ['label'] = 'Leisure Shop',
        ['coords'] = vector4(-1505.91, 1511.95, 115.29, 257.13),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Leisure Shop',
        ['products'] = Config.Products['leisureshop'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    ['police'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(461.8498, -981.0677, 30.6896, 91.5892),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(459.0441, -1008.0366, 28.2627, 271.4695),
        ['requiredJob'] = 'police',
    },

    ['ambulance'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(1660.81, 3660.0, 35.34, 71.0820),
        ['ped'] = 's_m_m_doctor_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(283.5821, -614.8570, 43.3792, 159.2903),
        ['requiredJob'] = 'ambulance'
    },

    ['ambulance1'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(-457.15, -309.71, 34.91, 71.0820),
        ['ped'] = 's_m_m_doctor_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(283.5821, -614.8570, 43.3792, 159.2903),
        ['requiredJob'] = 'ambulance'
    },

    ['mechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-343.66, -140.78, 39.02, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-354.3936, -128.2882, 39.4307, 251.4931),
        ['requiredJob'] = 'mechanic',
    },

    ['mechanic2'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(1189.36, 2641.00, 38.44, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(1189.9852, 2651.1873, 37.8351, 317.7137),
        ['requiredJob'] = 'mechanic2'
    },

    ['mechanic3'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-1156.56, -1999.85, 13.19, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-1131.9661, -1972.0144, 13.1603, 358.8637),
        ['requiredJob'] = 'mechanic3'
    },

    ['bennys'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-195.80, -1318.24, 31.08, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-232.5028, -1311.7202, 31.2960, 180.3716),
        ['requiredJob'] = 'bennys'
    },

    ['beeker'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(100.92, 6616.00, 32.47, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(119.3033, 6626.7358, 31.9558, 46.1566),
        ['requiredJob'] = 'beeker'
    },

    ['prison'] = {
        ['label'] = 'Canteen Shop',
        ['coords'] = vector4(1777.59, 2560.52, 44.62, 187.83),
        ['ped'] = false,
        ['products'] = Config.Products['prison'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1845.8175, 2585.9312, 45.6721, 96.7577)
    },

    ['blackmarket'] = {
        ['label'] = 'Black Market',
        ['coords'] = vector4(-594.7032, -1616.3647, 33.0105, 170.6846),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-clipboard',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['blackmarket'],
        ['delivery'] = vector4(-428.6385, -1728.1962, 19.7838, 75.6646)
    },

    -- mz-fishing Shop
    ["fishing"] = {
        ["label"] = "Boof Romano's Fish Merchant",
        ["coords"] = vector4(3803.69, 4440.73, 4.09, 4.39),
        ["ped"] = 's_m_m_migrant_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-fish-fins",
        ["targetLabel"] = "Sell Fish",
        ["products"] = Config.Products["fishing"],
        ["showblip"] = true,
        ["blipsprite"] = 68,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 47
    },
}
